version: 2
updates:
  # Swift Package Manager dependencies
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mpwg"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "swift"

  # Ruby dependencies for Fastlane
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mpwg"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mpwg"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"