# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  UI.header("In Before All")
  Dotenv.load '.env'
  UI.success("Loaded .env file")
  git_url = ENV['MATCH_GIT_URL']

app_store_connect_api_key(
   key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
   issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
   key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
   is_key_content_base64: true,
   in_house: false #boolean value if team is Enterprise or not
)
  UI.success("Loaded App Store Connect API Key")
end

desc "Sync certificates"
 lane :sync_certificates do

  sync_code_signing({readonly: true, type: "appstore")
 end

desc "Create ipa"
 lane :build_ios do
   #update profiles
   sync_certificates
   # Increases the build number by 1
   increment_build_number
   # Creates a signed file
#   clear_derived_data
   build_app(scheme: "Alles-Teurer", export_method: "app-store")
 end

desc "Create macos app"
lane :build_mac do
   #update profiles
   sync_certificates
   # Increases the build number by 1
   increment_build_number
   # Creates a signed file
#   clear_derived_data

   build_mac_app(scheme: "Alles-Teurer", export_method: "app-store",
   destination: 'platform=macOS,variant=Mac Catalyst',
   installer_cert_name: ENV["MAC_INSTALLER_CERT_NAME"],
   export_options: {
    provisioningProfiles: {
      "eu.mpwg.Alles-Teurer" => "match AppStore eu.mpwg.Alles-Teurer catalyst"
    }
  }
   )
end
